INSERT INTO transport_objects (
    id,
    title,
    transport_type_id,
    visit_status_id,
    country,
    region,
    city,
    latitude,
    longitude,
    description,
    notes,
    opened_year,
    operator,
    manufacturer,
    created_at,
    updated_at
) VALUES
(
    'vorobyovy-gory',
    'Канатная дорога на Воробьевых горах',
    'cable_urban',
    'not_visited',
    'Россия',
    'Москва',
    'Москва',
    55.7103,
    37.5517,
    'Городская канатная дорога через Москву-реку с видом на университет и стадион.',
    'Проверить расписание и семейный тариф перед поездкой.',
    NULL,
    NULL,
    NULL,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
),
(
    'nizhny-novgorod',
    'Нижегородская канатная дорога',
    'cable_aerial_tram',
    'not_visited',
    'Россия',
    'Нижний Новгород',
    'Нижний Новгород',
    56.3299,
    44.0186,
    'Маршрут над Волгой между Нижним Новгородом и Бором.',
    'Хороший кандидат для первой большой карточки с фото и билетами.',
    NULL,
    NULL,
    NULL,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
),
(
    'vladivostok-funicular',
    'Владивостокский фуникулер',
    'funicular_classic',
    'not_visited',
    'Россия',
    'Владивосток',
    'Владивосток',
    43.1187,
    131.8939,
    'Короткий городской фуникулер на сопке Орлиное Гнездо.',
    'Добавить историю сооружения и видовые точки.',
    NULL,
    NULL,
    NULL,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
ON CONFLICT(id) DO NOTHING;
