ICON_SIZE = 256
PADDING = 24
OUTLINE_RADIUS = 2
WIDE_CONTENT_ASPECT_RATIO = 1.25
TARGET_CONTENT_HEIGHT = 180
TARGET_CONTENT_ALPHA_AREA = 20000
TARGET_OUTLINED_ALPHA_AREA = 21500
OUTLINED_ALPHA_AREA_MIN = 13500
OUTLINED_ALPHA_AREA_MAX = 25000
MAX_CONTENT_SIDE = 248
MAX_WIDE_CONTENT_WIDTH = 248

MAX_OUTLINED_CONTENT_SIDE = MAX_CONTENT_SIDE + OUTLINE_RADIUS * 2
MAX_WIDE_OUTLINED_CONTENT_WIDTH = MAX_WIDE_CONTENT_WIDTH + OUTLINE_RADIUS * 2
TARGET_OUTLINED_CONTENT_HEIGHT = TARGET_CONTENT_HEIGHT + OUTLINE_RADIUS * 2
OUTLINED_BOTTOM_PADDING = PADDING - OUTLINE_RADIUS
