ICON_SIZE = 256
PADDING = 24
OUTLINE_RADIUS = 2
WIDE_CONTENT_ASPECT_RATIO = 1.25
MAX_CONTENT_SIDE = ICON_SIZE - PADDING * 2
MAX_WIDE_CONTENT_WIDTH = 184

MAX_OUTLINED_CONTENT_SIDE = MAX_CONTENT_SIDE + OUTLINE_RADIUS * 2
MAX_WIDE_OUTLINED_CONTENT_WIDTH = MAX_WIDE_CONTENT_WIDTH + OUTLINE_RADIUS * 2
OUTLINED_BOTTOM_PADDING = PADDING - OUTLINE_RADIUS
